export const SITE_MAP = {
  INDEX: 'HOME',

  CONTACT: 'CONTACT',

  PRODUCT: 'PRODUCT',
  INTRO: 'INTRO',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  CART: 'CART',
  ORDER: 'ORDER',
  DETAILS: 'DETAILS',
  PROFILE: 'PROFILE',
  ADDRESS: 'ADDRESS',
  PRODUCT_LIST: 'PRODUCT_LIST',
  FAVORITE: 'FAVORITE',
  RATINGSERVICE: 'RATINGSERVICE',
  REVIEWS: 'REVIEWS',
};
